# Imagem de Origem
FROM node:22-alpine AS build

# Diretório de trabalho (é onde a aplicação ficará dentro do container).
WORKDIR /app

# Variáveis de ambiente
ARG VITE_API_URL

ENV VITE_API_URL=$VITE_API_URL

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
