# Imagem de Origem
FROM node:22-alpine AS build

# Diretório de trabalho (é onde a aplicação ficará dentro do container).
WORKDIR /app

# Variáveis de ambiente
ARG VITE_API_URL

ENV VITE_API_URL=$VITE_API_URL

COPY package*.json .

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

CMD [ "npm", "run", "dev" ]
