server {
  listen 5173;
  listen [::]:5173;
  server_name localhost;
  #access_log /var/log/nginx/host.access.log main;
  
  location / {
  # Preflighted requests
    if ($request_method = OPTIONS ) {
      add_header "Access-Control-Allow-Origin" *;
      add_header "Access-Control-Allow-Methods" "GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD";
      add_header "Access-Control-Allow-Headers" "*";
      add_header 'Access-Control-Allow-Credentials' 'true';
      return 200;
    }
    root /usr/share/nginx/html;
    try_files $uri$args $uri$args/ /index.html; # React-JS redirect to Index.
  }

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
